name: glennc15-pytests-action
run-name: glennc15 pytests action
on:
  push:
    branches:
      - main
      - 'terraform/**'
      - 'tests/**'

env:
 AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  pytests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - uses: hashicorp/setup-terraform@v3

      - run: pip install -r requirements.txt
      - run: playwright install
      - run: cd terraform && terraform init -backend-config="access_key=$AWS_ACCESS_KEY_ID" -backend-config="secret_key=$AWS_SECRET_ACCESS_KEY"
      - run: cd ..
      - run: python build/project_build.py
      - run: URL=https://glenn15.com python -m pytest tests
      - run: URL=http://glenn15.com python -m pytest tests
      - run: URL=https://www.glenn15.com python -m pytest tests
      - run: URL=http://www.glenn15.com python -m pytest tests
