name: glennc15-pytests-action
run-name: glennc15 pytests action
on: [push]

jobs:
  pytests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - uses: hashicorp/setup-terraform@v3

      - run: pip install -r requirements.txt
      - run: playwright install
      - run: cd terraform && terraform init -backend-config="access_key=$ACCESS_KEY" -backend-config="secret_key=$SECRET_KEY"
      - run: cd ..
      - run: python build/project_build.py
      - run: URL=https://glenn15.com python -m pytest tests
      - run: URL=http://glenn15.com python -m pytest tests
      - run: URL=https://www.glenn15.com python -m pytest tests
      - run: URL=http://www.glenn15.com python -m pytest tests
